version: '3.8'
services:
    proxy:
        container_name: proxy
        restart: always
        image: googoo99/mmonstar_dev:release-proxy
        volumes:
            - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/proxy/sites-available:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"

    www_nginx:
        container_name: www_nginx
        image: nginx:latest
        expose:
            - "8080"
        volumes:
            - ./source/www:/source
            - ./nginx/www/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html

    www:
        container_name: www
        image: googoo99/mmonstar_dev:release-www
        expose:
            - "9000"
        volumes:
            - ./php/www/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/www/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    scm_nginx:
        container_name: scm_nginx
        image: nginx:latest
        expose:
            - "8081"
        volumes:
            - ./source/scm:/source
            - ./nginx/scm/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
    scm:
        container_name: scm
        image: googoo99/mmonstar_dev:release-www
        expose:
            - "9001"
        volumes:
            - ./php/scm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/scm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    api_nginx:
        container_name: api_nginx
        image: nginx:latest
        expose:
            - "8082"
        volumes:
            - ./source/api:/source
            - ./nginx/api/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
    api:
        container_name: api
        image: googoo99/mmonstar_dev:release-www
        expose:
            - "9002"
        volumes:
            - ./php/api/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/api/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    admin_nginx:
        container_name: admin_nginx
        image: nginx:latest
        expose:
            - "8083"
        volumes:
            - ./source/admin:/source
            - ./nginx/admin/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
    admin:
        container_name: admin
        image: googoo99/mmonstar_dev:release-www
        expose:
            - "9003"
        volumes:
            - ./php/admin/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/admin/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html