version: '3'
services:
    proxy:
        container_name: proxy
        restart: always
        build:
            context: ./nginx/proxy
            dockerfile: Dockerfile
        volumes:
            - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/proxy/sites-available:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"

    www_nginx:
        container_name: www_nginx
        image: nginx:latest
        expose:
            - "8080"
        volumes:
            - ./source/www:/source
            - ./nginx/www/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html

    www:
        container_name: www
        build:
            context: ./php/www
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - ./php/www/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/www/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    scm_nginx:
        container_name: scm_nginx
        image: nginx:latest
        expose:
            - "8081"
        volumes:
            - ./source/scm:/source
            - ./nginx/scm/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
    scm:
        container_name: scm
        build:
            context: ./php/scm
            dockerfile: Dockerfile
        expose:
            - "9001"
        volumes:
            - ./php/scm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/scm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    api_nginx:
        container_name: api_nginx
        image: nginx:latest
        expose:
            - "8082"
        volumes:
            - ./source/api:/source
            - ./nginx/api/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
    api:
        container_name: api
        build:
            context: ./php/api
            dockerfile: Dockerfile
        expose:
            - "9002"
        volumes:
            - ./php/api/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./php/api/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html
